{{- if and .Values.persistence.enabled .Values.persistence.hostPath (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jumble-api.fullname" . }}-db-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "jumble-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
{{- end -}}
