apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    app: rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: your-rest-api-image:latest
          ports:
            - name: http
              containerPort: 80
          env:
            - name: AUDIT_DB_URL
              value: your-audit-db-url
            - name: JUMBLE_DB_URL
              value: your-jumble-db-url
          args:
            - "--port=80"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            runAsUser: 1000
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: audit-secret-volume
              mountPath: /secrets/audit
              readOnly: true
            - name: jumble-secret-volume
              mountPath: /secrets/jumble
              readOnly: true
      volumes:
        - name: audit-secret-volume
          secret:
            secretName: audit-secret
        - name: jumble-secret-volume
          secret:
            secretName: jumble-secret
