apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumble-jumble-api
  labels:
    helm.sh/chart: jumble-api-0.0.1
    app.kubernetes.io/name: jumble-api
    app.kubernetes.io/instance: jumble
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jumble-api
      app.kubernetes.io/instance: jumble
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jumble-api
        app.kubernetes.io/instance: jumble
    spec:
      serviceAccountName: jumble-jumble-api
      securityContext:
        {}
      containers:
        - name: jumble-api
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - all
            runAsUser: 1000
          image: "mmurilo/scramble-words:0.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: MAX_CALLS
              value: "1000"
            - name: RETURN_LIMIT
              value: "10"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
