apiVersion: v1
kind: Service
metadata:
  name: jumble-jumble-api
  labels:
    helm.sh/chart: jumble-api-0.0.1
    app.kubernetes.io/name: jumble-api
    app.kubernetes.io/instance: jumble
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jumble-api
    app.kubernetes.io/instance: jumble
