name: Docker Image CI

on:
  push:
    paths-ignore:
      - "kubernetes"

  release:
    types: [published]

env:
  DOCKERHUB_PROJECT: scramble-words

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Load
        uses: docker/build-push-action@v4
        with:
          context: app
          load: true
          tags: ${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }} --help

      - name: Build and push Branch
        uses: docker/build-push-action@v4
        if: github.event_name == 'push'
        with:
          context: app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_PROJECT }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_PROJECT }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push latest
        uses: docker/build-push-action@v4
        if: github.event_name == 'release'
        with:
          context: app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_PROJECT }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_PROJECT }}:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_PROJECT }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
